# Files to skip in tests due to parsing issues
SKIP_FILES = c(
  "examples/knitr-examples/065-rmd-chunk.Rmd",
  "examples/quarto-cli/tests/docs/smoke-all/2023/03/17/4867.qmd",
  "examples/quarto-cli/tests/docs/smoke-all/fenced-div-reader-fixes/test-1.qmd"
)

update_tests = function(target, files, gen_func) {

  base_deps = c("helper-tests.R", "../../R/tests.R")

  if (!file.exists(target)) {
    writeLines(character(), target)
  }

  stopifnot(all(file.exists(c(target, base_deps, files))))

  outdated = purrr::map2_dbl(
    target, c(files, base_deps), ~ diff(file.info(c(.x, .y))$mtime)
  )

  if (any(outdated > 0)) {
    message("Generating ", target)
    purrr::map(
      files, ~ gen_func(.x, skip_files = SKIP_FILES)
    ) |>
      purrr::reduce(
        ~ c(.x, "", .y),
        .init = c(
          "# Generated by helper-tests.R, do not edit by hand",
          "",
          "if (!dir.exists('examples'))",
          "  skip('Additional example files not available')"
        )
      ) |>
      styler::style_text() |>
      writeLines(target)
  }
}

if (Sys.getenv("CI") == "" && file.exists("../../R/tests.R")) {
  # Only run if tests.R is younger than the output
  
  # Source the test generation functions
  source("../../R/tests.R")

  find_rmds = function(d) {
    fs::dir_ls(d, recurse = TRUE, regexp = ".*\\.[RrQq]md")
  }

  folders = c(`knitr` = "examples/knitr-examples/",
              `quarto-cli` = "examples/quarto-cli/",
              `quarto-web` = "examples/quarto-web/"
             ) |> 
            purrr::keep(dir.exists)
  
  purrr::walk2(
    folders, names(folders),
    function(d, name) {
      files = find_rmds(d)
      filename = paste0("test-examples-", name, "-round-trip.R")

      update_tests(
        filename, files, test_round_trip
      )
    }
  )
}
