// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// check_chunk_parser
Rcpp::List check_chunk_parser(std::string const& str);
RcppExport SEXP _rmdast_check_chunk_parser(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(check_chunk_parser(str));
    return rcpp_result_gen;
END_RCPP
}
// main
int main();
RcppExport SEXP _rmdast_main() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(main());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmdast_check_chunk_parser", (DL_FUNC) &_rmdast_check_chunk_parser, 1},
    {"_rmdast_main", (DL_FUNC) &_rmdast_main, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmdast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
