# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_name_parser <- function(str) {
    .Call(`_rmdast_check_name_parser`, str)
}

check_option_parser <- function(str) {
    .Call(`_rmdast_check_option_parser`, str)
}

check_option_list_parser <- function(str) {
    .Call(`_rmdast_check_option_list_parser`, str)
}

test <- function(str) {
    .Call(`_rmdast_test`, str)
}

